name: Build and Push Container Image

on:
  # Run automatically when you push to the main branch
  push:
    branches: [ "main" ]
  # Allow manual runs from the Actions tab
  workflow_dispatch:

env:
  # The image will be stored in GHCR under your username/repo_name
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push image from Containerfile
        uses: docker/build-push-action@v5
        with:
          # The context is the current directory, where the Containerfile is
          context: .
          file: ./Containerfile
          push: true
          # Tag the image with the unique git commit SHA
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
